### ISSUE TITLE
Changing the Style of SVG Defs is Broken on Safari 16.4

### ISSUE THREAD

**Issue by eyip002** [uniba-swt/LetSynchronise#145]
SVG defs are used in the task schedule to display arrow heads at the end of each dependency. On Safari 16.3 and earlier, the styling of the dependencies and their arrow heads would change together. On Safari 16.4, the styling of the arrow heads cannot be changed from their initial style.

Below, you can see that the arrow heads are red, even though they should change to blue (selected event chain) and orange (related event chains).

<img width="582" alt="Screenshot 2023-03-29 at 4 19 03 PM" src="https://user-images.githubusercontent.com/7035180/228589768-b2749c79-1390-4853-8ae2-04f585994425.png">

**Comment by eyip002** [comment]
Through luck, setting a bogus filter for each of the highlight styles triggers Safari 16.4 to update the colour of the SVG defs.

```css
#view-schedule path.relatedEventChainVisible {
    stroke: var(--bs-orange);
    stroke-width: 5px;
    marker-end: url(#arrowOrange);
    visibility: visible;
    filter: brightness(1);  /* setting a brightness(0) does not work */
}

#view-schedule path.eventChainVisible {
    stroke: var(--bs-blue);
    stroke-width: 5px;
    marker-end: url(#arrowBlue);
    visibility: visible;
    filter: brightness(0);
}
```
